import { IService } from '../../models/i-service';

export const services = [
  {
    title: 'services.web_development.title',
    description: 'services.web_development.description',
    keyServices: [
      'services.web_development.key_services.0',
      'services.web_development.key_services.1',
      'services.web_development.key_services.2',
      'services.web_development.key_services.3',
      'services.web_development.key_services.4',
    ],
    image: 'web-development.webp',
  },
  {
    title: 'services.cloud_solutions.title',
    description: 'services.cloud_solutions.description',
    keyServices: [
      'services.cloud_solutions.key_services.0',
      'services.cloud_solutions.key_services.1',
      'services.cloud_solutions.key_services.2',
      'services.cloud_solutions.key_services.3',
      'services.cloud_solutions.key_services.4',
      'services.cloud_solutions.key_services.5',
    ],
    image: 'cloud-solutions.webp',
  },
  {
    title: 'services.it_consulting.title',
    description: 'services.it_consulting.description',
    keyServices: [
      'services.it_consulting.key_services.0',
      'services.it_consulting.key_services.1',
      'services.it_consulting.key_services.2',
      'services.it_consulting.key_services.3',
      'services.it_consulting.key_services.4',
    ],
    image: 'it-consulting.webp',
  },
  {
    title: 'services.custom_software_development.title',
    description: 'services.custom_software_development.description',
    keyServices: [
      'services.custom_software_development.key_services.0',
      'services.custom_software_development.key_services.1',
      'services.custom_software_development.key_services.2',
      'services.custom_software_development.key_services.3',
      'services.custom_software_development.key_services.4',
      'services.custom_software_development.key_services.5',
      'services.custom_software_development.key_services.6',
      'services.custom_software_development.key_services.7',
    ],
    image: 'custom-software-development.webp',
  },
  {
    title: 'services.mobile_app_development.title',
    description: 'services.mobile_app_development.description',
    keyServices: [
      'services.mobile_app_development.key_services.0',
      'services.mobile_app_development.key_services.1',
      'services.mobile_app_development.key_services.2',
      'services.mobile_app_development.key_services.3',
      'services.mobile_app_development.key_services.4',
      'services.mobile_app_development.key_services.5',
    ],
    image: 'mobile-app-development.webp',
  },
  {
    title: 'services.frontend_development.title',
    description: 'services.frontend_development.description',
    keyServices: [
      'services.frontend_development.key_services.0',
      'services.frontend_development.key_services.1',
      'services.frontend_development.key_services.2',
      'services.frontend_development.key_services.3',
      'services.frontend_development.key_services.4',
      'services.frontend_development.key_services.5',
    ],
    image: 'frontend-development.webp',
  },
  {
    title: 'services.backend_development.title',
    description: 'services.backend_development.description',
    keyServices: [
      'services.backend_development.key_services.0',
      'services.backend_development.key_services.1',
      'services.backend_development.key_services.2',
      'services.backend_development.key_services.3',
      'services.backend_development.key_services.4',
      'services.backend_development.key_services.5',
    ],
    image: 'backend-development.webp',
  },
  {
    title: 'services.database_management.title',
    description: 'services.database_management.description',
    keyServices: [
      'services.database_management.key_services.0',
      'services.database_management.key_services.1',
      'services.database_management.key_services.2',
      'services.database_management.key_services.3',
      'services.database_management.key_services.4',
    ],
    image: 'database-management.webp',
  },
  {
    title: 'services.devops_and_automation.title',
    description: 'services.devops_and_automation.description',
    keyServices: [
      'services.devops_and_automation.key_services.0',
      'services.devops_and_automation.key_services.1',
      'services.devops_and_automation.key_services.2',
      'services.devops_and_automation.key_services.3',
      'services.devops_and_automation.key_services.4',
      'services.devops_and_automation.key_services.5',
    ],
    image: 'dev-ops-and-automation.webp',
  },
  {
    title: 'services.technical_support.title',
    description: 'services.technical_support.description',
    keyServices: [
      'services.technical_support.key_services.0',
      'services.technical_support.key_services.1',
      'services.technical_support.key_services.2',
      'services.technical_support.key_services.3',
      'services.technical_support.key_services.4',
    ],
    image: 'technical-support.webp',
  },
] as IService[];
